apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  selector:
    matchLabels:
      run: my-nginx-label
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-label
    spec:
      containers:
        - name: my-nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    run: my-nginx-label
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30081
  selector:
    run: my-nginx-label
